"""
Precedent retrieval — the channel `retrieve()` was always meant to have.

Similar RESOLVED tickets, by similarity over subject+body. Distinct from
retrieve_policy.py, which answers "which clause governs this" over prose.
Two channels, two failure modes, kept apart all the way into state.

Backend is nomic-embed-text via Ollama, reusing grounding.py's embedding
path so there is one embedding stack in this repo, not two. Falls back to
lexical overlap when Ollama is absent — and SAYS SO, because a silent
fallback to a weaker method is how a system quietly stops working.

    from precedents import PrecedentIndex
    idx = PrecedentIndex()            # reads precedent_pool.csv
    hits = idx.lookup(subject, body, k=5)

LEAKAGE. make_datasets.py asserts the gold tickets are excluded from the
pool, so no graded ticket can retrieve its own answer. This module re-checks
that at load time rather than trusting it, because the assertion runs at
build time and the file can be regenerated by hand.

THE POISON CASE. The retrieve() docstring names it: a precedent whose own
label is wrong contaminates every ticket that retrieves it. Every hit
carries its ticket_id, so `precedents_used` in the audit record lets you
find which ones did the damage after the fact.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

POOL = "precedent_pool.csv"
GOLD = "gold_set_template.csv"

# Placeholder. Derive it the way calibrate_grounding.py derives the grounding
# bands — from hand-checked neighbours on your own gold set — then flip
# SIM_DERIVED. Until then every result says the floor is uncalibrated.
MIN_SIM = 0.35
SIM_DERIVED = False

def _load_threshold() -> None:
    global MIN_SIM, SIM_DERIVED
    import json, pathlib as _pl
    f = _pl.Path("gate_thresholds.json")
    if not f.exists():
        return
    try:
        d = json.loads(f.read_text())
    except Exception:
        return
    if "min_sim" in d:
        MIN_SIM = float(d["min_sim"]["min_sim"])
        SIM_DERIVED = True


_load_threshold()

STOP = set(
    """a an the and or but if then than that this these those is are was were be
been being do does did have has had having will would shall should can could may
might must to of in on at by for with from as it its no not so such very more
most other some any each both all when where which who whom whose what why how i
you he she they we me him her them us our your their there here about into over
under again my mine ours yours""".split()
)


def _terms(text: str) -> set[str]:
    ws = re.findall(r"[a-z][a-z0-9'-]{2,}", (text or "").lower())
    return {w for w in ws if w not in STOP}


@dataclass
class Precedent:
    ticket_id: str
    text: str
    priority: str
    score: float
    method: str
    queue: str = ""

    def as_dict(self) -> dict:
        # `answer` is the field name classifier.build_messages() reads.
        return {
            "ticket_id": self.ticket_id,
            "priority": self.priority,
            "queue": self.queue,
            "answer": self.text[:400],
            "score": round(self.score, 3),
            "method": self.method,
        }


class PrecedentIndex:
    def __init__(self, pool_path: str | Path = POOL, gold_path: str | Path = GOLD):
        self.pool_path = Path(pool_path)
        self.load_error: str | None = None
        self.leakage: list[str] = []
        self.method = "lexical"
        self._rows: list[dict] = []
        self._vecs = None
        self._term_sets: list[set[str]] = []
        self._load(Path(gold_path))

    def _load(self, gold_path: Path) -> None:
        try:
            import pandas as pd
            df = pd.read_csv(self.pool_path)
        except Exception as exc:
            self.load_error = f"{type(exc).__name__}: {exc}"
            return

        self._rows = df.to_dict("records")
        self._term_sets = [_terms(str(r.get("text", ""))) for r in self._rows]

        # Re-check leakage rather than trusting the build-time assertion.
        if gold_path.exists():
            try:
                import pandas as pd
                g = set(pd.read_csv(gold_path).ticket_id.astype(str))
                self.leakage = sorted(
                    {str(r["ticket_id"]) for r in self._rows} & g
                )
            except Exception:
                pass

        # Embeddings are optional. If Ollama is not up, stay lexical and say so.
        try:
            import grounding
            if grounding._backend() != "lexical":
                import numpy as np
                texts = [str(r.get("text", "")) for r in self._rows]
                self._vecs = np.array(grounding._embed(texts))
                self.method = f"embedding:{grounding._backend()}"
        except Exception:
            self._vecs = None
            self.method = "lexical-fallback"

    # ---------------------------------------------------------------- lookup

    def lookup(self, subject: str | None, body: str, *, k: int = 5) -> list[Precedent]:
        """
        Returns [] rather than low-scoring filler. An empty list is
        information; a bad neighbour is contamination.
        """
        if self.load_error or not self._rows:
            return []
        q = f"{subject or ''} {body or ''}".strip()
        if not q:
            return []

        if self._vecs is not None:
            try:
                import numpy as np
                import grounding
                qv = np.array(grounding._embed([q])[0])
                sims = self._vecs @ qv
            except Exception:
                sims = None
        else:
            sims = None

        if sims is None:
            qt = _terms(q)
            sims = [
                (len(qt & ts) / len(qt | ts)) if (qt | ts) else 0.0
                for ts in self._term_sets
            ]
            method = "lexical-fallback"
        else:
            method = self.method

        scored = [
            Precedent(
                ticket_id=str(r.get("ticket_id")),
                text=str(r.get("text", "")),
                priority=str(r.get("priority", "")),
                queue=str(r.get("queue", "")),
                score=float(s),
                method=method,
            )
            for r, s in zip(self._rows, sims)
            if float(s) >= MIN_SIM
        ]
        scored.sort(key=lambda p: -p.score)
        return scored[:k]

    # ----------------------------------------------------------------- flags

    def flags(self, hits: list[Precedent]) -> list[str]:
        f: list[str] = []
        if self.load_error:
            return ["precedent_index_unavailable"]
        if self.leakage:
            # Loud, because this one invalidates every number downstream.
            f.append("precedent_pool_contains_gold_tickets")
        if not hits:
            f.append("precedent_none_found")
        if hits and all(h.method.startswith("lexical") for h in hits):
            f.append("precedent_lexical_fallback")
        if hits and len({h.priority for h in hits}) > 1:
            # Neighbours that disagree with each other are weak evidence, and
            # the model should not be told they agree.
            f.append("precedent_labels_disagree")
        if not SIM_DERIVED:
            f.append("precedent_similarity_floor_not_calibrated")
        return f


_INDEX: PrecedentIndex | None = None


def index() -> PrecedentIndex:
    global _INDEX
    if _INDEX is None:
        _INDEX = PrecedentIndex()
    return _INDEX
